### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by kranack**
Add French to changelog translations.

### CODE REVIEW

**Comment by 9999years** [comment]
Thanks so much for this! How would you like to be credited as? Does `Damien Calesse <github.com/kranack>` sound good or is there an email you prefer?

**Comment by kranack** [comment]
Well, `Damien Calesse <github.com/kranack>` sounds good to me, thanks :)

**Comment by 9999years** [comment]
Merged and published as v2.3.0; uploaded to CTAN, should be live within 24-48 hours. Thanks again for your contribution!

**Comment by 9999years** [comment]
> Hello Rebecca,
> 
> Thanks for this upload:
> 
> > Package:        changelog [found]
> > Type:           announce [found]
> > Version:        2.3.0 2020-08-26
> > Author:         Rebecca Turner
> > Location:       /macros/latex/contrib/changelog [unmodified]
> > License:        gpl3 [unmodified]
> 
> I've installed the new version and updated the catalogue repository.
> 
> The changes should become available on the mirrors within the next 24
> hours. Then I will post this announcement:
> 
> > Announcement:
> > Thanks to the new French Translations by Damien Calesse (github.com/kranack), changelog is now translated to German (Holger Schieferdecker), Spanish (David Arnold <dar@xoe.solutions>), and French as well as the original English strings.
> 
> 
> Kind regards
> Erik Braun
> 
> for the CTAN Team

**Pull request merged**
