### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by blaggacao**

### CODE REVIEW

**Comment by blaggacao** [comment]
@9999years ping ping... Hope everything's well!

I thought I'd prepare another commit with a translation of the "Changelog" section title itself.

**Comment by blaggacao** [comment]
If you where to accept #4  t's spanish translation would be: `Registro de cambios`

**Comment by 9999years** [comment]
Hey, so sorry for the delay. Merged!

**Comment by 9999years** [comment]
Sent version 2.2.0 with your changes to CTAN, it should be up in 24-48 hours. Thanks again for the contribution!

**Pull request merged**
